### ISSUE TITLE
Require components instead of all the ZF2 in composer.json

### ISSUE THREAD

**Issue by bfolliot** [Soflomo/Purifier#5]
It is useless to load the entire framework.

**Comment by Saeven** [comment]
Yes that'd be great.  Any chance you can get this done Jurian? With the advent of 2.5, it's really a pita.

**Comment by Saeven** [comment]
@bfolliot seems inactive, so for the time being I made a fork and put it up on Packagist, you're welcome to use it: https://packagist.org/packages/saeven/zf2-purifier

**Comment by juriansluiman** [comment]
@bfolliot @Saeven Sorry guys, I can update the thing for you. The issue is I am not working for Soflomo anymore. I have had this issue with other projects which seem now abandoned here as well.

@Saeven your PR just removes any zf2 dependency, while the purifier has some real deps. Can you adjust your PR to require only the zf2 filter component? Afaik the SM and view should be optional dependencies if you want to, only filter is required here.

**Comment by juriansluiman** [comment]
BTW, for Mail I made juriansluiman/Soflomo-Mail which I can maintain freely, so I might want to do that with Purifier too. Also, if any of you is willing to take on some maintenance as well (though it's very minor) I can add one of you as collaborator then as well.

**Comment by jurreantonisse** [comment]
@juriansluiman still has access, and I agree with updates. I don't have the expertise myself so new contributors are welcome.

**Comment by Saeven** [comment]
@juriansluiman pull updated, I can certainly help with the maintenance as I use it actively and would like to avoid the need to resort to a personal fork.

**Comment by jurreantonisse** [comment]
@Saeven Great! With permission of @juriansluiman your very welcome with maintenance.
